@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.3 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Mar 03 14:56:08 -0500 2020
REM SW Build 2405991 on Thu Dec  6 23:38:27 MST 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
call xsim Value_Grabber_tb_behav -key {Behavioral:sim_1:Functional:Value_Grabber_tb} -tclbatch Value_Grabber_tb.tcl -protoinst "protoinst_files/Value_Grabber.protoinst" -protoinst "protoinst_files/Segment_Decoder_Score.protoinst" -protoinst "protoinst_files/Segment_Decoder_V_L.protoinst" -protoinst "protoinst_files/BTN_Debounce.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
