#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2018.3 (64-bit)
#
# Filename    : Win_Conditions.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Sun Feb 23 22:58:19 -0500 2020
# SW Build 2405991 on Thu Dec  6 23:38:27 MST 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved. 
#
# usage: Win_Conditions.sh [-help]
# usage: Win_Conditions.sh [-lib_map_path]
# usage: Win_Conditions.sh [-noclean_files]
# usage: Win_Conditions.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'Win_Conditions.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xil_defaultlib xlconcat_v2_1_1)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "Win_Conditions.sh - Script generated by export_simulation (Vivado v2018.3 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../bd/Win_Conditions/ipshared/debf/xup_or5.srcs/sources_1/new/xup_or5.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_or5_0_0/sim/Win_Conditions_xup_or5_0_0.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_or5_0_1/sim/Win_Conditions_xup_or5_0_1.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_or5_0_2/sim/Win_Conditions_xup_or5_0_2.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_or5_0_3/sim/Win_Conditions_xup_or5_0_3.v" \
    "$ref_dir/../../../bd/Win_Conditions/ipshared/1eaf/xup_or4.srcs/sources_1/new/xup_or4.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_or4_0_0/sim/Win_Conditions_xup_or4_0_0.v" \
    "$ref_dir/../../../bd/Win_Conditions/ipshared/77ea/xup_and4.srcs/sources_1/new/xup_and4.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_0_27/sim/Win_Conditions_xup_and4_0_27.v" \
    "$ref_dir/../../../bd/Win_Conditions/ipshared/ded9/xup_or3.srcs/sources_1/new/xup_or3.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_or3_0_11/sim/Win_Conditions_xup_or3_0_11.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_1_22/sim/Win_Conditions_xup_and4_1_22.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_3_10/sim/Win_Conditions_xup_and4_3_10.v" \
    "$ref_dir/../../../bd/Win_Conditions/ipshared/778c/xup_and2.srcs/sources_1/new/xup_and2.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and2_0_12/sim/Win_Conditions_xup_and2_0_12.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and2_1_11/sim/Win_Conditions_xup_and2_1_11.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and2_2_10/sim/Win_Conditions_xup_and2_2_10.v" \
    "$ref_dir/../../../bd/Win_Conditions/ipshared/e3e7/xup_inv.srcs/sources_1/new/xup_inv.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_0_17/sim/Win_Conditions_xup_inv_0_17.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_5_1/sim/Win_Conditions_xup_inv_5_1.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_3_1/sim/Win_Conditions_xup_inv_3_1.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_7_5/sim/Win_Conditions_xup_inv_7_5.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_4_1/sim/Win_Conditions_xup_inv_4_1.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_1_1/sim/Win_Conditions_xup_inv_1_1.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_8_5/sim/Win_Conditions_xup_inv_8_5.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_9_2/sim/Win_Conditions_xup_inv_9_2.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_11_1/sim/Win_Conditions_xup_inv_11_1.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_0_42/sim/Win_Conditions_xup_and4_0_42.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_1_37/sim/Win_Conditions_xup_and4_1_37.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_2_15/sim/Win_Conditions_xup_and4_2_15.v" \
    "$ref_dir/../../../bd/Win_Conditions/ipshared/b79c/xup_and3.srcs/sources_1/new/xup_and3.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and3_0_16/sim/Win_Conditions_xup_and3_0_16.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_2_17/sim/Win_Conditions_xup_inv_2_17.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_3_17/sim/Win_Conditions_xup_inv_3_17.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_6_17/sim/Win_Conditions_xup_inv_6_17.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_7_21/sim/Win_Conditions_xup_inv_7_21.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_10_18/sim/Win_Conditions_xup_inv_10_18.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_11_17/sim/Win_Conditions_xup_inv_11_17.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_0_28/sim/Win_Conditions_xup_and4_0_28.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_or3_0_12/sim/Win_Conditions_xup_or3_0_12.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_1_23/sim/Win_Conditions_xup_and4_1_23.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_3_11/sim/Win_Conditions_xup_and4_3_11.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and2_0_13/sim/Win_Conditions_xup_and2_0_13.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and2_1_12/sim/Win_Conditions_xup_and2_1_12.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and2_2_11/sim/Win_Conditions_xup_and2_2_11.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_0_18/sim/Win_Conditions_xup_inv_0_18.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_5_2/sim/Win_Conditions_xup_inv_5_2.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_4_2/sim/Win_Conditions_xup_inv_4_2.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_1_2/sim/Win_Conditions_xup_inv_1_2.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_8_6/sim/Win_Conditions_xup_inv_8_6.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_9_3/sim/Win_Conditions_xup_inv_9_3.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_0_43/sim/Win_Conditions_xup_and4_0_43.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_1_38/sim/Win_Conditions_xup_and4_1_38.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_2_16/sim/Win_Conditions_xup_and4_2_16.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and3_0_17/sim/Win_Conditions_xup_and3_0_17.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_0_36/sim/Win_Conditions_xup_inv_0_36.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_1_18/sim/Win_Conditions_xup_inv_1_18.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_3_18/sim/Win_Conditions_xup_inv_3_18.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_4_18/sim/Win_Conditions_xup_inv_4_18.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_5_18/sim/Win_Conditions_xup_inv_5_18.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_7_22/sim/Win_Conditions_xup_inv_7_22.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_8_22/sim/Win_Conditions_xup_inv_8_22.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_9_19/sim/Win_Conditions_xup_inv_9_19.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_11_18/sim/Win_Conditions_xup_inv_11_18.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_0_29/sim/Win_Conditions_xup_and4_0_29.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_or3_0_13/sim/Win_Conditions_xup_or3_0_13.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_1_24/sim/Win_Conditions_xup_and4_1_24.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_3_12/sim/Win_Conditions_xup_and4_3_12.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and2_0_14/sim/Win_Conditions_xup_and2_0_14.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and2_1_13/sim/Win_Conditions_xup_and2_1_13.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and2_2_12/sim/Win_Conditions_xup_and2_2_12.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_0_19/sim/Win_Conditions_xup_inv_0_19.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_3_3/sim/Win_Conditions_xup_inv_3_3.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_7_7/sim/Win_Conditions_xup_inv_7_7.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_4_3/sim/Win_Conditions_xup_inv_4_3.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_6_3/sim/Win_Conditions_xup_inv_6_3.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_2_3/sim/Win_Conditions_xup_inv_2_3.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_8_7/sim/Win_Conditions_xup_inv_8_7.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_10_3/sim/Win_Conditions_xup_inv_10_3.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_11_3/sim/Win_Conditions_xup_inv_11_3.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_0_44/sim/Win_Conditions_xup_and4_0_44.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_1_39/sim/Win_Conditions_xup_and4_1_39.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_2_17/sim/Win_Conditions_xup_and4_2_17.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and3_0_18/sim/Win_Conditions_xup_and3_0_18.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_1_19/sim/Win_Conditions_xup_inv_1_19.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_3_19/sim/Win_Conditions_xup_inv_3_19.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_5_19/sim/Win_Conditions_xup_inv_5_19.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_7_23/sim/Win_Conditions_xup_inv_7_23.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_9_20/sim/Win_Conditions_xup_inv_9_20.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_11_19/sim/Win_Conditions_xup_inv_11_19.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_0_30/sim/Win_Conditions_xup_and4_0_30.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_or3_0_14/sim/Win_Conditions_xup_or3_0_14.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_1_25/sim/Win_Conditions_xup_and4_1_25.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_3_13/sim/Win_Conditions_xup_and4_3_13.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and2_0_15/sim/Win_Conditions_xup_and2_0_15.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and2_1_14/sim/Win_Conditions_xup_and2_1_14.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and2_2_13/sim/Win_Conditions_xup_and2_2_13.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_0_20/sim/Win_Conditions_xup_inv_0_20.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_4_4/sim/Win_Conditions_xup_inv_4_4.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_6_4/sim/Win_Conditions_xup_inv_6_4.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_2_4/sim/Win_Conditions_xup_inv_2_4.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_8_8/sim/Win_Conditions_xup_inv_8_8.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_10_4/sim/Win_Conditions_xup_inv_10_4.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_0_45/sim/Win_Conditions_xup_and4_0_45.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_1_40/sim/Win_Conditions_xup_and4_1_40.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_2_18/sim/Win_Conditions_xup_and4_2_18.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and3_0_19/sim/Win_Conditions_xup_and3_0_19.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_0_38/sim/Win_Conditions_xup_inv_0_38.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_3_20/sim/Win_Conditions_xup_inv_3_20.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_4_20/sim/Win_Conditions_xup_inv_4_20.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_7_24/sim/Win_Conditions_xup_inv_7_24.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_8_24/sim/Win_Conditions_xup_inv_8_24.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_11_20/sim/Win_Conditions_xup_inv_11_20.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_0_31/sim/Win_Conditions_xup_and4_0_31.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_or3_0_15/sim/Win_Conditions_xup_or3_0_15.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_1_26/sim/Win_Conditions_xup_and4_1_26.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_3_14/sim/Win_Conditions_xup_and4_3_14.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and2_0_16/sim/Win_Conditions_xup_and2_0_16.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and2_1_15/sim/Win_Conditions_xup_and2_1_15.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and2_2_14/sim/Win_Conditions_xup_and2_2_14.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_0_21/sim/Win_Conditions_xup_inv_0_21.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_3_5/sim/Win_Conditions_xup_inv_3_5.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_7_9/sim/Win_Conditions_xup_inv_7_9.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_4_5/sim/Win_Conditions_xup_inv_4_5.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_8_9/sim/Win_Conditions_xup_inv_8_9.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_11_5/sim/Win_Conditions_xup_inv_11_5.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_0_46/sim/Win_Conditions_xup_and4_0_46.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_1_41/sim/Win_Conditions_xup_and4_1_41.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_2_19/sim/Win_Conditions_xup_and4_2_19.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and3_0_20/sim/Win_Conditions_xup_and3_0_20.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_3_21/sim/Win_Conditions_xup_inv_3_21.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_7_25/sim/Win_Conditions_xup_inv_7_25.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_11_21/sim/Win_Conditions_xup_inv_11_21.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_0_32/sim/Win_Conditions_xup_and4_0_32.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_or3_0_16/sim/Win_Conditions_xup_or3_0_16.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_1_27/sim/Win_Conditions_xup_and4_1_27.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_3_15/sim/Win_Conditions_xup_and4_3_15.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and2_0_17/sim/Win_Conditions_xup_and2_0_17.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and2_1_16/sim/Win_Conditions_xup_and2_1_16.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and2_2_15/sim/Win_Conditions_xup_and2_2_15.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_0_22/sim/Win_Conditions_xup_inv_0_22.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_4_6/sim/Win_Conditions_xup_inv_4_6.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_8_10/sim/Win_Conditions_xup_inv_8_10.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_0_47/sim/Win_Conditions_xup_and4_0_47.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_1_42/sim/Win_Conditions_xup_and4_1_42.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_2_20/sim/Win_Conditions_xup_and4_2_20.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and3_0_21/sim/Win_Conditions_xup_and3_0_21.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_10_23/sim/Win_Conditions_xup_inv_10_23.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_8_26/sim/Win_Conditions_xup_inv_8_26.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_6_22/sim/Win_Conditions_xup_inv_6_22.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_5_22/sim/Win_Conditions_xup_inv_5_22.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_4_22/sim/Win_Conditions_xup_inv_4_22.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_2_22/sim/Win_Conditions_xup_inv_2_22.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_1_22/sim/Win_Conditions_xup_inv_1_22.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_0_40/sim/Win_Conditions_xup_inv_0_40.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_9_23/sim/Win_Conditions_xup_inv_9_23.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_0_33/sim/Win_Conditions_xup_and4_0_33.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_or3_0_17/sim/Win_Conditions_xup_or3_0_17.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_1_28/sim/Win_Conditions_xup_and4_1_28.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_3_16/sim/Win_Conditions_xup_and4_3_16.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and2_0_18/sim/Win_Conditions_xup_and2_0_18.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and2_1_17/sim/Win_Conditions_xup_and2_1_17.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and2_2_16/sim/Win_Conditions_xup_and2_2_16.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_5_7/sim/Win_Conditions_xup_inv_5_7.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_3_7/sim/Win_Conditions_xup_inv_3_7.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_7_11/sim/Win_Conditions_xup_inv_7_11.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_6_7/sim/Win_Conditions_xup_inv_6_7.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_1_7/sim/Win_Conditions_xup_inv_1_7.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_2_7/sim/Win_Conditions_xup_inv_2_7.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_10_7/sim/Win_Conditions_xup_inv_10_7.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_9_8/sim/Win_Conditions_xup_inv_9_8.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_11_7/sim/Win_Conditions_xup_inv_11_7.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_0_48/sim/Win_Conditions_xup_and4_0_48.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_1_43/sim/Win_Conditions_xup_and4_1_43.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_2_21/sim/Win_Conditions_xup_and4_2_21.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and3_0_22/sim/Win_Conditions_xup_and3_0_22.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_1_23/sim/Win_Conditions_xup_inv_1_23.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_2_23/sim/Win_Conditions_xup_inv_2_23.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_5_23/sim/Win_Conditions_xup_inv_5_23.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_6_23/sim/Win_Conditions_xup_inv_6_23.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_9_24/sim/Win_Conditions_xup_inv_9_24.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_10_24/sim/Win_Conditions_xup_inv_10_24.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_0_34/sim/Win_Conditions_xup_and4_0_34.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_or3_0_18/sim/Win_Conditions_xup_or3_0_18.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_1_29/sim/Win_Conditions_xup_and4_1_29.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_3_17/sim/Win_Conditions_xup_and4_3_17.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and2_0_19/sim/Win_Conditions_xup_and2_0_19.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and2_1_18/sim/Win_Conditions_xup_and2_1_18.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and2_2_17/sim/Win_Conditions_xup_and2_2_17.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_5_8/sim/Win_Conditions_xup_inv_5_8.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_6_8/sim/Win_Conditions_xup_inv_6_8.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_1_8/sim/Win_Conditions_xup_inv_1_8.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_2_8/sim/Win_Conditions_xup_inv_2_8.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_10_8/sim/Win_Conditions_xup_inv_10_8.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_9_9/sim/Win_Conditions_xup_inv_9_9.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_0_4/sim/Win_Conditions_xup_and4_0_4.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_1_1/sim/Win_Conditions_xup_and4_1_1.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_2_1/sim/Win_Conditions_xup_and4_2_1.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and3_0_2/sim/Win_Conditions_xup_and3_0_2.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_0_27/sim/Win_Conditions_xup_inv_0_27.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_1_11/sim/Win_Conditions_xup_inv_1_11.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_2_11/sim/Win_Conditions_xup_inv_2_11.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_3_11/sim/Win_Conditions_xup_inv_3_11.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_4_11/sim/Win_Conditions_xup_inv_4_11.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_5_11/sim/Win_Conditions_xup_inv_5_11.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_6_11/sim/Win_Conditions_xup_inv_6_11.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_7_15/sim/Win_Conditions_xup_inv_7_15.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_8_15/sim/Win_Conditions_xup_inv_8_15.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_9_12/sim/Win_Conditions_xup_inv_9_12.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_10_11/sim/Win_Conditions_xup_inv_10_11.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_11_11/sim/Win_Conditions_xup_inv_11_11.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_0_13/sim/Win_Conditions_xup_and4_0_13.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_or3_0_0/sim/Win_Conditions_xup_or3_0_0.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_0_14/sim/Win_Conditions_xup_and4_0_14.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_1_10/sim/Win_Conditions_xup_and4_1_10.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and2_0_0/sim/Win_Conditions_xup_and2_0_0.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and2_0_1/sim/Win_Conditions_xup_and2_0_1.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and2_1_0/sim/Win_Conditions_xup_and2_1_0.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_0_8/sim/Win_Conditions_xup_inv_0_8.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_0_13/sim/Win_Conditions_xup_inv_0_13.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_0_11/sim/Win_Conditions_xup_inv_0_11.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_0_15/sim/Win_Conditions_xup_inv_0_15.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_0_12/sim/Win_Conditions_xup_inv_0_12.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_0_14/sim/Win_Conditions_xup_inv_0_14.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_0_9/sim/Win_Conditions_xup_inv_0_9.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_0_10/sim/Win_Conditions_xup_inv_0_10.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_8_0/sim/Win_Conditions_xup_inv_8_0.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_8_2/sim/Win_Conditions_xup_inv_8_2.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_8_3/sim/Win_Conditions_xup_inv_8_3.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_9_0/sim/Win_Conditions_xup_inv_9_0.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_0_40/sim/Win_Conditions_xup_and4_0_40.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_1_35/sim/Win_Conditions_xup_and4_1_35.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_2_13/sim/Win_Conditions_xup_and4_2_13.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and3_0_14/sim/Win_Conditions_xup_and3_0_14.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_1_15/sim/Win_Conditions_xup_inv_1_15.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_2_15/sim/Win_Conditions_xup_inv_2_15.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_3_15/sim/Win_Conditions_xup_inv_3_15.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_5_15/sim/Win_Conditions_xup_inv_5_15.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_6_15/sim/Win_Conditions_xup_inv_6_15.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_7_19/sim/Win_Conditions_xup_inv_7_19.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_9_16/sim/Win_Conditions_xup_inv_9_16.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_10_16/sim/Win_Conditions_xup_inv_10_16.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_11_15/sim/Win_Conditions_xup_inv_11_15.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_0_26/sim/Win_Conditions_xup_and4_0_26.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_or3_0_10/sim/Win_Conditions_xup_or3_0_10.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_1_21/sim/Win_Conditions_xup_and4_1_21.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_3_9/sim/Win_Conditions_xup_and4_3_9.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and2_0_11/sim/Win_Conditions_xup_and2_0_11.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and2_1_10/sim/Win_Conditions_xup_and2_1_10.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and2_2_9/sim/Win_Conditions_xup_and2_2_9.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_0_16/sim/Win_Conditions_xup_inv_0_16.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_5_0/sim/Win_Conditions_xup_inv_5_0.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_4_0/sim/Win_Conditions_xup_inv_4_0.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_6_0/sim/Win_Conditions_xup_inv_6_0.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_1_0/sim/Win_Conditions_xup_inv_1_0.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_2_0/sim/Win_Conditions_xup_inv_2_0.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_8_4/sim/Win_Conditions_xup_inv_8_4.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_10_0/sim/Win_Conditions_xup_inv_10_0.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_9_1/sim/Win_Conditions_xup_inv_9_1.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_0_41/sim/Win_Conditions_xup_and4_0_41.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_1_36/sim/Win_Conditions_xup_and4_1_36.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and4_2_14/sim/Win_Conditions_xup_and4_2_14.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_and3_0_15/sim/Win_Conditions_xup_and3_0_15.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_0_34/sim/Win_Conditions_xup_inv_0_34.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_2_16/sim/Win_Conditions_xup_inv_2_16.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_3_16/sim/Win_Conditions_xup_inv_3_16.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_4_16/sim/Win_Conditions_xup_inv_4_16.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_6_16/sim/Win_Conditions_xup_inv_6_16.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_7_20/sim/Win_Conditions_xup_inv_7_20.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_8_20/sim/Win_Conditions_xup_inv_8_20.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_10_17/sim/Win_Conditions_xup_inv_10_17.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xup_inv_11_16/sim/Win_Conditions_xup_inv_11_16.v" \
    "$ref_dir/../../../bd/Win_Conditions/sim/Win_Conditions.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconcat_v2_1_1 $vlogan_opts +v2k \
    "$ref_dir/../../../../SlotMachine.srcs/sources_1/bd/Win_Conditions/ipshared/2f66/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xlconcat_0_0/sim/Win_Conditions_xlconcat_0_0.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xlconcat_1_0/sim/Win_Conditions_xlconcat_1_0.v" \
    "$ref_dir/../../../bd/Win_Conditions/ip/Win_Conditions_xlconcat_2_0/sim/Win_Conditions_xlconcat_2_0.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.Win_Conditions xil_defaultlib.glbl -o Win_Conditions_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./Win_Conditions_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./Win_Conditions.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key Win_Conditions_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc Win_Conditions_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./Win_Conditions.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: Win_Conditions.sh [-help]\n\
Usage: Win_Conditions.sh [-lib_map_path]\n\
Usage: Win_Conditions.sh [-reset_run]\n\
Usage: Win_Conditions.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
