# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pins.xdc

# Block Designs: bd/Seg_Decoder/Seg_Decoder.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Seg_Decoder || ORIG_REF_NAME==Seg_Decoder} -quiet] -quiet

# IP: bd/Seg_Decoder/ip/Seg_Decoder_xup_inv_0_0/Seg_Decoder_xup_inv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Seg_Decoder_xup_inv_0_0 || ORIG_REF_NAME==Seg_Decoder_xup_inv_0_0} -quiet] -quiet

# IP: bd/Seg_Decoder/ip/Seg_Decoder_xup_inv_1_0/Seg_Decoder_xup_inv_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Seg_Decoder_xup_inv_1_0 || ORIG_REF_NAME==Seg_Decoder_xup_inv_1_0} -quiet] -quiet

# IP: bd/Seg_Decoder/ip/Seg_Decoder_xup_inv_2_0/Seg_Decoder_xup_inv_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Seg_Decoder_xup_inv_2_0 || ORIG_REF_NAME==Seg_Decoder_xup_inv_2_0} -quiet] -quiet

# IP: bd/Seg_Decoder/ip/Seg_Decoder_xup_inv_3_0/Seg_Decoder_xup_inv_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Seg_Decoder_xup_inv_3_0 || ORIG_REF_NAME==Seg_Decoder_xup_inv_3_0} -quiet] -quiet

# IP: bd/Seg_Decoder/ip/Seg_Decoder_xup_inv_4_0/Seg_Decoder_xup_inv_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Seg_Decoder_xup_inv_4_0 || ORIG_REF_NAME==Seg_Decoder_xup_inv_4_0} -quiet] -quiet

# IP: bd/Seg_Decoder/ip/Seg_Decoder_xup_and3_0_0/Seg_Decoder_xup_and3_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Seg_Decoder_xup_and3_0_0 || ORIG_REF_NAME==Seg_Decoder_xup_and3_0_0} -quiet] -quiet

# IP: bd/Seg_Decoder/ip/Seg_Decoder_xup_and4_0_0/Seg_Decoder_xup_and4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Seg_Decoder_xup_and4_0_0 || ORIG_REF_NAME==Seg_Decoder_xup_and4_0_0} -quiet] -quiet

# IP: bd/Seg_Decoder/ip/Seg_Decoder_xup_or2_0_0/Seg_Decoder_xup_or2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Seg_Decoder_xup_or2_0_0 || ORIG_REF_NAME==Seg_Decoder_xup_or2_0_0} -quiet] -quiet

# IP: bd/Seg_Decoder/ip/Seg_Decoder_xup_xor2_0_0/Seg_Decoder_xup_xor2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Seg_Decoder_xup_xor2_0_0 || ORIG_REF_NAME==Seg_Decoder_xup_xor2_0_0} -quiet] -quiet

# IP: bd/Seg_Decoder/ip/Seg_Decoder_xup_and2_0_0/Seg_Decoder_xup_and2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Seg_Decoder_xup_and2_0_0 || ORIG_REF_NAME==Seg_Decoder_xup_and2_0_0} -quiet] -quiet

# IP: bd/Seg_Decoder/ip/Seg_Decoder_xup_and3_0_1/Seg_Decoder_xup_and3_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Seg_Decoder_xup_and3_0_1 || ORIG_REF_NAME==Seg_Decoder_xup_and3_0_1} -quiet] -quiet

# IP: bd/Seg_Decoder/ip/Seg_Decoder_xup_inv_0_1/Seg_Decoder_xup_inv_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Seg_Decoder_xup_inv_0_1 || ORIG_REF_NAME==Seg_Decoder_xup_inv_0_1} -quiet] -quiet

# IP: bd/Seg_Decoder/ip/Seg_Decoder_xup_inv_1_1/Seg_Decoder_xup_inv_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Seg_Decoder_xup_inv_1_1 || ORIG_REF_NAME==Seg_Decoder_xup_inv_1_1} -quiet] -quiet

# IP: bd/Seg_Decoder/ip/Seg_Decoder_xup_and4_0_1/Seg_Decoder_xup_and4_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Seg_Decoder_xup_and4_0_1 || ORIG_REF_NAME==Seg_Decoder_xup_and4_0_1} -quiet] -quiet

# IP: bd/Seg_Decoder/ip/Seg_Decoder_xup_xor2_0_1/Seg_Decoder_xup_xor2_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Seg_Decoder_xup_xor2_0_1 || ORIG_REF_NAME==Seg_Decoder_xup_xor2_0_1} -quiet] -quiet

# IP: bd/Seg_Decoder/ip/Seg_Decoder_xup_inv_0_2/Seg_Decoder_xup_inv_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Seg_Decoder_xup_inv_0_2 || ORIG_REF_NAME==Seg_Decoder_xup_inv_0_2} -quiet] -quiet

# IP: bd/Seg_Decoder/ip/Seg_Decoder_xup_inv_1_2/Seg_Decoder_xup_inv_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Seg_Decoder_xup_inv_1_2 || ORIG_REF_NAME==Seg_Decoder_xup_inv_1_2} -quiet] -quiet

# IP: bd/Seg_Decoder/ip/Seg_Decoder_xup_inv_2_1/Seg_Decoder_xup_inv_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Seg_Decoder_xup_inv_2_1 || ORIG_REF_NAME==Seg_Decoder_xup_inv_2_1} -quiet] -quiet

# IP: bd/Seg_Decoder/ip/Seg_Decoder_xup_and2_0_1/Seg_Decoder_xup_and2_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Seg_Decoder_xup_and2_0_1 || ORIG_REF_NAME==Seg_Decoder_xup_and2_0_1} -quiet] -quiet

# IP: bd/Seg_Decoder/ip/Seg_Decoder_xup_inv_3_1/Seg_Decoder_xup_inv_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Seg_Decoder_xup_inv_3_1 || ORIG_REF_NAME==Seg_Decoder_xup_inv_3_1} -quiet] -quiet

# IP: bd/Seg_Decoder/ip/Seg_Decoder_xup_or2_0_1/Seg_Decoder_xup_or2_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Seg_Decoder_xup_or2_0_1 || ORIG_REF_NAME==Seg_Decoder_xup_or2_0_1} -quiet] -quiet

# IP: bd/Seg_Decoder/ip/Seg_Decoder_xup_inv_0_3/Seg_Decoder_xup_inv_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Seg_Decoder_xup_inv_0_3 || ORIG_REF_NAME==Seg_Decoder_xup_inv_0_3} -quiet] -quiet

# IP: bd/Seg_Decoder/ip/Seg_Decoder_xup_and2_0_2/Seg_Decoder_xup_and2_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Seg_Decoder_xup_and2_0_2 || ORIG_REF_NAME==Seg_Decoder_xup_and2_0_2} -quiet] -quiet

# IP: bd/Seg_Decoder/ip/Seg_Decoder_xup_or2_0_2/Seg_Decoder_xup_or2_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Seg_Decoder_xup_or2_0_2 || ORIG_REF_NAME==Seg_Decoder_xup_or2_0_2} -quiet] -quiet

# IP: bd/Seg_Decoder/ip/Seg_Decoder_xup_inv_0_4/Seg_Decoder_xup_inv_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Seg_Decoder_xup_inv_0_4 || ORIG_REF_NAME==Seg_Decoder_xup_inv_0_4} -quiet] -quiet

# IP: bd/Seg_Decoder/ip/Seg_Decoder_xup_inv_2_2/Seg_Decoder_xup_inv_2_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Seg_Decoder_xup_inv_2_2 || ORIG_REF_NAME==Seg_Decoder_xup_inv_2_2} -quiet] -quiet

# IP: bd/Seg_Decoder/ip/Seg_Decoder_xup_and2_0_3/Seg_Decoder_xup_and2_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Seg_Decoder_xup_and2_0_3 || ORIG_REF_NAME==Seg_Decoder_xup_and2_0_3} -quiet] -quiet

# IP: bd/Seg_Decoder/ip/Seg_Decoder_xup_or2_0_3/Seg_Decoder_xup_or2_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Seg_Decoder_xup_or2_0_3 || ORIG_REF_NAME==Seg_Decoder_xup_or2_0_3} -quiet] -quiet

# IP: bd/Seg_Decoder/ip/Seg_Decoder_xup_and2_1_0/Seg_Decoder_xup_and2_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Seg_Decoder_xup_and2_1_0 || ORIG_REF_NAME==Seg_Decoder_xup_and2_1_0} -quiet] -quiet

# IP: bd/Seg_Decoder/ip/Seg_Decoder_xup_and2_2_0/Seg_Decoder_xup_and2_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Seg_Decoder_xup_and2_2_0 || ORIG_REF_NAME==Seg_Decoder_xup_and2_2_0} -quiet] -quiet

# IP: bd/Seg_Decoder/ip/Seg_Decoder_xup_or2_1_0/Seg_Decoder_xup_or2_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Seg_Decoder_xup_or2_1_0 || ORIG_REF_NAME==Seg_Decoder_xup_or2_1_0} -quiet] -quiet

# IP: bd/Seg_Decoder/ip/Seg_Decoder_xup_and3_0_2/Seg_Decoder_xup_and3_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Seg_Decoder_xup_and3_0_2 || ORIG_REF_NAME==Seg_Decoder_xup_and3_0_2} -quiet] -quiet

# IP: bd/Seg_Decoder/ip/Seg_Decoder_xup_and3_1_0/Seg_Decoder_xup_and3_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Seg_Decoder_xup_and3_1_0 || ORIG_REF_NAME==Seg_Decoder_xup_and3_1_0} -quiet] -quiet

# IP: bd/Seg_Decoder/ip/Seg_Decoder_xup_inv_0_5/Seg_Decoder_xup_inv_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Seg_Decoder_xup_inv_0_5 || ORIG_REF_NAME==Seg_Decoder_xup_inv_0_5} -quiet] -quiet

# IP: bd/Seg_Decoder/ip/Seg_Decoder_xup_inv_1_3/Seg_Decoder_xup_inv_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Seg_Decoder_xup_inv_1_3 || ORIG_REF_NAME==Seg_Decoder_xup_inv_1_3} -quiet] -quiet

# IP: bd/Seg_Decoder/ip/Seg_Decoder_xup_inv_2_3/Seg_Decoder_xup_inv_2_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Seg_Decoder_xup_inv_2_3 || ORIG_REF_NAME==Seg_Decoder_xup_inv_2_3} -quiet] -quiet

# IP: bd/Seg_Decoder/ip/Seg_Decoder_xup_or2_0_4/Seg_Decoder_xup_or2_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Seg_Decoder_xup_or2_0_4 || ORIG_REF_NAME==Seg_Decoder_xup_or2_0_4} -quiet] -quiet

# XDC: bd/Seg_Decoder/Seg_Decoder_ooc.xdc
