# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: W:/EGR_224/EGR_224/EGR_224_Slot_Machine_Project/SlotMachine/SlotMachine.srcs/sources_1/bd/multiplexer/ip/multiplexer_c_counter_binary_0_1/multiplexer_c_counter_binary_0_1.xci
# IP: The module: 'multiplexer_c_counter_binary_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: w:/EGR_224/EGR_224/EGR_224_Slot_Machine_Project/SlotMachine/SlotMachine.srcs/sources_1/bd/multiplexer/ip/multiplexer_c_counter_binary_0_1/multiplexer_c_counter_binary_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'multiplexer_c_counter_binary_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: W:/EGR_224/EGR_224/EGR_224_Slot_Machine_Project/SlotMachine/SlotMachine.srcs/sources_1/bd/multiplexer/ip/multiplexer_c_counter_binary_0_1/multiplexer_c_counter_binary_0_1.xci
# IP: The module: 'multiplexer_c_counter_binary_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: w:/EGR_224/EGR_224/EGR_224_Slot_Machine_Project/SlotMachine/SlotMachine.srcs/sources_1/bd/multiplexer/ip/multiplexer_c_counter_binary_0_1/multiplexer_c_counter_binary_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'multiplexer_c_counter_binary_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
