# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Adder/Adder.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adder || ORIG_REF_NAME==Adder} -quiet] -quiet

# IP: bd/Adder/ip/Adder_xup_xor2_1_0/Adder_xup_xor2_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adder_xup_xor2_1_0 || ORIG_REF_NAME==Adder_xup_xor2_1_0} -quiet] -quiet

# IP: bd/Adder/ip/Adder_xup_and2_0_0/Adder_xup_and2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adder_xup_and2_0_0 || ORIG_REF_NAME==Adder_xup_and2_0_0} -quiet] -quiet

# IP: bd/Adder/ip/Adder_xup_xor2_0_0/Adder_xup_xor2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adder_xup_xor2_0_0 || ORIG_REF_NAME==Adder_xup_xor2_0_0} -quiet] -quiet

# IP: bd/Adder/ip/Adder_xup_and2_1_0/Adder_xup_and2_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adder_xup_and2_1_0 || ORIG_REF_NAME==Adder_xup_and2_1_0} -quiet] -quiet

# IP: bd/Adder/ip/Adder_xup_xor2_2_0/Adder_xup_xor2_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adder_xup_xor2_2_0 || ORIG_REF_NAME==Adder_xup_xor2_2_0} -quiet] -quiet

# IP: bd/Adder/ip/Adder_xup_or2_0_0/Adder_xup_or2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adder_xup_or2_0_0 || ORIG_REF_NAME==Adder_xup_or2_0_0} -quiet] -quiet

# IP: bd/Adder/ip/Adder_xup_xor2_1_1/Adder_xup_xor2_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adder_xup_xor2_1_1 || ORIG_REF_NAME==Adder_xup_xor2_1_1} -quiet] -quiet

# IP: bd/Adder/ip/Adder_xup_and2_0_1/Adder_xup_and2_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adder_xup_and2_0_1 || ORIG_REF_NAME==Adder_xup_and2_0_1} -quiet] -quiet

# IP: bd/Adder/ip/Adder_xup_xor2_0_1/Adder_xup_xor2_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adder_xup_xor2_0_1 || ORIG_REF_NAME==Adder_xup_xor2_0_1} -quiet] -quiet

# IP: bd/Adder/ip/Adder_xup_and2_1_1/Adder_xup_and2_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adder_xup_and2_1_1 || ORIG_REF_NAME==Adder_xup_and2_1_1} -quiet] -quiet

# IP: bd/Adder/ip/Adder_xup_xor2_2_1/Adder_xup_xor2_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adder_xup_xor2_2_1 || ORIG_REF_NAME==Adder_xup_xor2_2_1} -quiet] -quiet

# IP: bd/Adder/ip/Adder_xup_or2_0_1/Adder_xup_or2_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adder_xup_or2_0_1 || ORIG_REF_NAME==Adder_xup_or2_0_1} -quiet] -quiet

# IP: bd/Adder/ip/Adder_xlconstant_0_0/Adder_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adder_xlconstant_0_0 || ORIG_REF_NAME==Adder_xlconstant_0_0} -quiet] -quiet

# IP: bd/Adder/ip/Adder_xlconcat_0_0/Adder_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adder_xlconcat_0_0 || ORIG_REF_NAME==Adder_xlconcat_0_0} -quiet] -quiet

# IP: bd/Adder/ip/Adder_xlslice_0_0/Adder_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adder_xlslice_0_0 || ORIG_REF_NAME==Adder_xlslice_0_0} -quiet] -quiet

# IP: bd/Adder/ip/Adder_xlslice_0_1/Adder_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adder_xlslice_0_1 || ORIG_REF_NAME==Adder_xlslice_0_1} -quiet] -quiet

# IP: bd/Adder/ip/Adder_xlslice_0_2/Adder_xlslice_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adder_xlslice_0_2 || ORIG_REF_NAME==Adder_xlslice_0_2} -quiet] -quiet

# IP: bd/Adder/ip/Adder_xlslice_0_3/Adder_xlslice_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adder_xlslice_0_3 || ORIG_REF_NAME==Adder_xlslice_0_3} -quiet] -quiet

# XDC: bd/Adder/Adder_ooc.xdc
