# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pins.xdc

# Block Designs: bd/One_Digit/One_Digit.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit || ORIG_REF_NAME==One_Digit} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_clk_divider_15_0/One_Digit_xup_clk_divider_15_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_clk_divider_15_0 || ORIG_REF_NAME==One_Digit_xup_clk_divider_15_0} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_clk_divider_2_0/One_Digit_xup_clk_divider_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_clk_divider_2_0 || ORIG_REF_NAME==One_Digit_xup_clk_divider_2_0} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_clk_divider_16_0/One_Digit_xup_clk_divider_16_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_clk_divider_16_0 || ORIG_REF_NAME==One_Digit_xup_clk_divider_16_0} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_clk_divider_3_0/One_Digit_xup_clk_divider_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_clk_divider_3_0 || ORIG_REF_NAME==One_Digit_xup_clk_divider_3_0} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_clk_divider_17_0/One_Digit_xup_clk_divider_17_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_clk_divider_17_0 || ORIG_REF_NAME==One_Digit_xup_clk_divider_17_0} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_clk_divider_4_0/One_Digit_xup_clk_divider_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_clk_divider_4_0 || ORIG_REF_NAME==One_Digit_xup_clk_divider_4_0} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_clk_divider_18_0/One_Digit_xup_clk_divider_18_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_clk_divider_18_0 || ORIG_REF_NAME==One_Digit_xup_clk_divider_18_0} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_clk_divider_5_0/One_Digit_xup_clk_divider_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_clk_divider_5_0 || ORIG_REF_NAME==One_Digit_xup_clk_divider_5_0} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_clk_divider_19_0/One_Digit_xup_clk_divider_19_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_clk_divider_19_0 || ORIG_REF_NAME==One_Digit_xup_clk_divider_19_0} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_clk_divider_6_0/One_Digit_xup_clk_divider_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_clk_divider_6_0 || ORIG_REF_NAME==One_Digit_xup_clk_divider_6_0} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_clk_divider_7_0/One_Digit_xup_clk_divider_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_clk_divider_7_0 || ORIG_REF_NAME==One_Digit_xup_clk_divider_7_0} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_clk_divider_20_0/One_Digit_xup_clk_divider_20_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_clk_divider_20_0 || ORIG_REF_NAME==One_Digit_xup_clk_divider_20_0} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_clk_divider_8_0/One_Digit_xup_clk_divider_8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_clk_divider_8_0 || ORIG_REF_NAME==One_Digit_xup_clk_divider_8_0} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_clk_divider_21_0/One_Digit_xup_clk_divider_21_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_clk_divider_21_0 || ORIG_REF_NAME==One_Digit_xup_clk_divider_21_0} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_clk_divider_9_0/One_Digit_xup_clk_divider_9_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_clk_divider_9_0 || ORIG_REF_NAME==One_Digit_xup_clk_divider_9_0} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_clk_divider_22_0/One_Digit_xup_clk_divider_22_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_clk_divider_22_0 || ORIG_REF_NAME==One_Digit_xup_clk_divider_22_0} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_clk_divider_10_0/One_Digit_xup_clk_divider_10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_clk_divider_10_0 || ORIG_REF_NAME==One_Digit_xup_clk_divider_10_0} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_clk_divider_23_0/One_Digit_xup_clk_divider_23_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_clk_divider_23_0 || ORIG_REF_NAME==One_Digit_xup_clk_divider_23_0} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_clk_divider_11_0/One_Digit_xup_clk_divider_11_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_clk_divider_11_0 || ORIG_REF_NAME==One_Digit_xup_clk_divider_11_0} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_clk_divider_24_0/One_Digit_xup_clk_divider_24_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_clk_divider_24_0 || ORIG_REF_NAME==One_Digit_xup_clk_divider_24_0} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_clk_divider_12_0/One_Digit_xup_clk_divider_12_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_clk_divider_12_0 || ORIG_REF_NAME==One_Digit_xup_clk_divider_12_0} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_clk_divider_25_0/One_Digit_xup_clk_divider_25_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_clk_divider_25_0 || ORIG_REF_NAME==One_Digit_xup_clk_divider_25_0} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_clk_divider_13_0/One_Digit_xup_clk_divider_13_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_clk_divider_13_0 || ORIG_REF_NAME==One_Digit_xup_clk_divider_13_0} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_clk_divider_0_0/One_Digit_xup_clk_divider_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_clk_divider_0_0 || ORIG_REF_NAME==One_Digit_xup_clk_divider_0_0} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_clk_divider_26_0/One_Digit_xup_clk_divider_26_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_clk_divider_26_0 || ORIG_REF_NAME==One_Digit_xup_clk_divider_26_0} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_clk_divider_14_0/One_Digit_xup_clk_divider_14_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_clk_divider_14_0 || ORIG_REF_NAME==One_Digit_xup_clk_divider_14_0} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_clk_divider_1_0/One_Digit_xup_clk_divider_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_clk_divider_1_0 || ORIG_REF_NAME==One_Digit_xup_clk_divider_1_0} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_c_counter_binary_0_0/One_Digit_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_c_counter_binary_0_0 || ORIG_REF_NAME==One_Digit_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_and3_0_0/One_Digit_xup_and3_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_and3_0_0 || ORIG_REF_NAME==One_Digit_xup_and3_0_0} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_and4_0_0/One_Digit_xup_and4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_and4_0_0 || ORIG_REF_NAME==One_Digit_xup_and4_0_0} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_inv_0_0/One_Digit_xup_inv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_inv_0_0 || ORIG_REF_NAME==One_Digit_xup_inv_0_0} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_inv_1_0/One_Digit_xup_inv_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_inv_1_0 || ORIG_REF_NAME==One_Digit_xup_inv_1_0} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_inv_2_0/One_Digit_xup_inv_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_inv_2_0 || ORIG_REF_NAME==One_Digit_xup_inv_2_0} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_inv_3_0/One_Digit_xup_inv_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_inv_3_0 || ORIG_REF_NAME==One_Digit_xup_inv_3_0} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_inv_4_0/One_Digit_xup_inv_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_inv_4_0 || ORIG_REF_NAME==One_Digit_xup_inv_4_0} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_or2_0_0/One_Digit_xup_or2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_or2_0_0 || ORIG_REF_NAME==One_Digit_xup_or2_0_0} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_and2_0_0/One_Digit_xup_and2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_and2_0_0 || ORIG_REF_NAME==One_Digit_xup_and2_0_0} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_xor2_0_0/One_Digit_xup_xor2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_xor2_0_0 || ORIG_REF_NAME==One_Digit_xup_xor2_0_0} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_and3_0_1/One_Digit_xup_and3_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_and3_0_1 || ORIG_REF_NAME==One_Digit_xup_and3_0_1} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_inv_0_1/One_Digit_xup_inv_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_inv_0_1 || ORIG_REF_NAME==One_Digit_xup_inv_0_1} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_inv_1_1/One_Digit_xup_inv_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_inv_1_1 || ORIG_REF_NAME==One_Digit_xup_inv_1_1} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_and2_0_1/One_Digit_xup_and2_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_and2_0_1 || ORIG_REF_NAME==One_Digit_xup_and2_0_1} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_and4_0_1/One_Digit_xup_and4_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_and4_0_1 || ORIG_REF_NAME==One_Digit_xup_and4_0_1} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_inv_0_2/One_Digit_xup_inv_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_inv_0_2 || ORIG_REF_NAME==One_Digit_xup_inv_0_2} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_inv_1_2/One_Digit_xup_inv_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_inv_1_2 || ORIG_REF_NAME==One_Digit_xup_inv_1_2} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_inv_2_1/One_Digit_xup_inv_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_inv_2_1 || ORIG_REF_NAME==One_Digit_xup_inv_2_1} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_inv_3_1/One_Digit_xup_inv_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_inv_3_1 || ORIG_REF_NAME==One_Digit_xup_inv_3_1} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_or2_0_1/One_Digit_xup_or2_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_or2_0_1 || ORIG_REF_NAME==One_Digit_xup_or2_0_1} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_xor2_0_1/One_Digit_xup_xor2_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_xor2_0_1 || ORIG_REF_NAME==One_Digit_xup_xor2_0_1} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_and2_0_2/One_Digit_xup_and2_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_and2_0_2 || ORIG_REF_NAME==One_Digit_xup_and2_0_2} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_inv_0_3/One_Digit_xup_inv_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_inv_0_3 || ORIG_REF_NAME==One_Digit_xup_inv_0_3} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_or2_0_2/One_Digit_xup_or2_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_or2_0_2 || ORIG_REF_NAME==One_Digit_xup_or2_0_2} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_and2_0_3/One_Digit_xup_and2_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_and2_0_3 || ORIG_REF_NAME==One_Digit_xup_and2_0_3} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_and2_1_0/One_Digit_xup_and2_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_and2_1_0 || ORIG_REF_NAME==One_Digit_xup_and2_1_0} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_and2_2_0/One_Digit_xup_and2_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_and2_2_0 || ORIG_REF_NAME==One_Digit_xup_and2_2_0} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_inv_0_4/One_Digit_xup_inv_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_inv_0_4 || ORIG_REF_NAME==One_Digit_xup_inv_0_4} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_inv_2_2/One_Digit_xup_inv_2_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_inv_2_2 || ORIG_REF_NAME==One_Digit_xup_inv_2_2} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_or2_0_3/One_Digit_xup_or2_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_or2_0_3 || ORIG_REF_NAME==One_Digit_xup_or2_0_3} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_or2_1_0/One_Digit_xup_or2_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_or2_1_0 || ORIG_REF_NAME==One_Digit_xup_or2_1_0} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_and3_0_2/One_Digit_xup_and3_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_and3_0_2 || ORIG_REF_NAME==One_Digit_xup_and3_0_2} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_and3_1_0/One_Digit_xup_and3_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_and3_1_0 || ORIG_REF_NAME==One_Digit_xup_and3_1_0} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_inv_0_5/One_Digit_xup_inv_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_inv_0_5 || ORIG_REF_NAME==One_Digit_xup_inv_0_5} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_inv_1_3/One_Digit_xup_inv_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_inv_1_3 || ORIG_REF_NAME==One_Digit_xup_inv_1_3} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_inv_2_3/One_Digit_xup_inv_2_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_inv_2_3 || ORIG_REF_NAME==One_Digit_xup_inv_2_3} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xup_or2_0_4/One_Digit_xup_or2_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xup_or2_0_4 || ORIG_REF_NAME==One_Digit_xup_or2_0_4} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xlslice_0_1/One_Digit_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xlslice_0_1 || ORIG_REF_NAME==One_Digit_xlslice_0_1} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xlslice_0_2/One_Digit_xlslice_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xlslice_0_2 || ORIG_REF_NAME==One_Digit_xlslice_0_2} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xlslice_0_3/One_Digit_xlslice_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xlslice_0_3 || ORIG_REF_NAME==One_Digit_xlslice_0_3} -quiet] -quiet

# IP: bd/One_Digit/ip/One_Digit_xlslice_0_4/One_Digit_xlslice_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==One_Digit_xlslice_0_4 || ORIG_REF_NAME==One_Digit_xlslice_0_4} -quiet] -quiet

# XDC: bd/One_Digit/One_Digit_ooc.xdc
