# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/garzamor/EGR224/EGR_224_Lab5_/counter/counter.srcs/sources_1/bd/Decade_counter/ip/Decade_counter_c_counter_binary_0_0/Decade_counter_c_counter_binary_0_0.xci
# IP: The module: 'Decade_counter_c_counter_binary_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/garzamor/EGR224/EGR_224_Lab5_/counter/counter.srcs/sources_1/bd/Decade_counter/ip/Decade_counter_c_counter_binary_0_0/Decade_counter_c_counter_binary_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Decade_counter_c_counter_binary_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/garzamor/EGR224/EGR_224_Lab5_/counter/counter.srcs/sources_1/bd/Decade_counter/ip/Decade_counter_c_counter_binary_0_0/Decade_counter_c_counter_binary_0_0.xci
# IP: The module: 'Decade_counter_c_counter_binary_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/garzamor/EGR224/EGR_224_Lab5_/counter/counter.srcs/sources_1/bd/Decade_counter/ip/Decade_counter_c_counter_binary_0_0/Decade_counter_c_counter_binary_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Decade_counter_c_counter_binary_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
