set_property PACKAGE_PIN U2 [get_ports {AN0_0[0]}]
set_property PACKAGE_PIN U4 [get_ports {AN1_0[0]}]
set_property PACKAGE_PIN V4 [get_ports {AN2_0[0]}]
set_property PACKAGE_PIN W4 [get_ports {AN3_0[0]}]
set_property PACKAGE_PIN W7 [get_ports A]
set_property PACKAGE_PIN W6 [get_ports B]
set_property PACKAGE_PIN U8 [get_ports C]
set_property PACKAGE_PIN V8 [get_ports D]
set_property PACKAGE_PIN U5 [get_ports E]
set_property PACKAGE_PIN V5 [get_ports F]
set_property PACKAGE_PIN U7 [get_ports G]
set_property IOSTANDARD LVCMOS33 [get_ports {AN0_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN1_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN2_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN3_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports A]
set_property IOSTANDARD LVCMOS33 [get_ports B]
set_property IOSTANDARD LVCMOS33 [get_ports clk_in]
set_property IOSTANDARD LVCMOS33 [get_ports C]
set_property IOSTANDARD LVCMOS33 [get_ports D]
set_property IOSTANDARD LVCMOS33 [get_ports E]
set_property IOSTANDARD LVCMOS33 [get_ports F]
set_property IOSTANDARD LVCMOS33 [get_ports G]

set_property PACKAGE_PIN W5 [get_ports clk_in]

set_property IOSTANDARD LVCMOS33 [get_ports clkin]
set_property PACKAGE_PIN W5 [get_ports clkin]
