set_property SRC_FILE_INFO {cfile:C:/Users/garzamor/EGR224/EGR_224_Lab5_/counter/counter.srcs/constrs_1/new/pins.xdc rfile:../counter.srcs/constrs_1/new/pins.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W7 [get_ports clkout]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports clkout]
